[project]
name = "monorepo"
version = "0.1.0"
dependencies = [
    # Image Processing
    "albumentations>=0.5,<=1.4",
    "opencv-python-headless>=4.0",
    "pillow>=9.0",
    "imagesize>=1.2",

    # Math
    "numpy>=1.26",
    "pandas>=1.0",

    # Deep Learning Frameworks
    "torch>=1.7,<=2.3",
    "torchaudio>=1.7,<=2.3",
    "torchtext>=0.6,<=0.18",
    "torchvision>=0.6,<=0.18",
    "timm==0.5.4",

    # Natural Language Processing
    "transformers>=4.0",
    "tokenizers>=0.13",
    "x-transformers==0.15",

    # Utilities
    "tqdm>=4.0",
    "einops>=0.3",
    "PyYAML>=5.0",
    "requests>=2.0",
    "munch>=2.0",
    "pyreadline3>=3.0; sys_platform == 'win32'",
    "python-Levenshtein>=0.12",
    "wandb>=0.19"
]

[tool.setuptools]
packages = ["train", "collector"]